swagger: "2.0"
info:
  description: |
    HackZurich 2019 API
  title: HackZurich 2019
  version: 1.0.0
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
basePath: /api/v1

definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string
      path:
        type: string

  gameDescription:
    type: object
    properties:
      id:
        type: string
        description: Game ID
      status:
        type: string
        description: Status of the game
        enum:
          - ACTIVE
          - PAUSED
          - FINISHED
  gameState:
    type: object
    properties:
      count:
        type: number
        format: integer
        description: Pinguin count
      countShip:
        type: number
        format: integer
        description: Ship count
      ships:
        type: array
        items:
          $ref: "#/definitions/point"
      countFarm:
        type: number
        format: integer
        description: Ship count
      farms:
        type: array
        items:
          $ref: "#/definitions/point"

  point:
    type: object
    properties:
      lat:
        type: number
      lng:
        type: number

paths:
  /game:
    post:
      operationId: startGame
      summary: Start the game
      tags:
        - game
      responses:
        200:
          description: Game started
          schema:
            $ref: "#/definitions/gameDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"

  /game/{game_id}:
    get:
      operationId: getGameDescription
      summary: Get game description
      tags:
        - game
      parameters:
        - type: string
          name: game_id
          in: path
          required: true
      responses:
        200:
          description: Description
          schema:
            $ref: "#/definitions/gameDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"

  /game/{game_id}/pause:
    post:
      operationId: pauseGame
      summary: Pause the game
      tags:
        - game
      parameters:
        - type: string
          name: game_id
          in: path
          required: true
      responses:
        200:
          description: Paused
          schema:
            $ref: "#/definitions/gameDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"

  /game/{game_id}/resume:
    post:
      operationId: resumeGame
      summary: Resume the game
      tags:
        - game
      parameters:
        - type: string
          name: game_id
          in: path
          required: true
      responses:
        200:
          description: Resumed
          schema:
            $ref: "#/definitions/gameDescription"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"

  /game/{game_id}/state:
    get:
      operationId: getGameState
      summary: Get state of the game
      tags:
        - game
      parameters:
        - type: string
          name: game_id
          in: path
          required: true
      responses:
        200:
          description: Game state
          schema:
            $ref: "#/definitions/gameState"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"

  /game/{game_id}/destroy:
    post:
      operationId: destroyDisaster
      summary: Destroy disaster on the map
      tags:
        - game
      parameters:
        - type: string
          name: game_id
          in: path
          required: true
        - name: goal
          in: body
          schema:
            $ref: "#/definitions/point"
          required: true
      responses:
        200:
          description: Destroyed
          schema:
            $ref: "#/definitions/gameState"
        default:
          description: Error
          schema:
            $ref: "#/definitions/error"
